SoPra-Team-17/Server

.gitmodules, CMakeLists.txt, exampleConfig/characters.json, exampleConfig/matchconfig.json, exampleConfig/scenario.json, installDependencies.sh, src/main.cpp, test/CMakeLists.txt, test/client/CMakeLists.txt, test/client/main.cpp
=> Integrate network library

CMakeLists.txt, src/main.cpp, src/network/MessageRouter.cpp, src/network/MessageRouter.hpp
=> add MessageRouter class

src/CMakeLists.txt, src/Events.hpp, src/GameFSM.hpp, src/Server.cpp, src/Server.hpp, src/ServerUtil.hpp, src/main.cpp, src/network/MessageRouter.cpp, src/network/MessageRouter.hpp, src/util/Player.cpp, src/util/Player.hpp, test/client/CMakeLists.txt, test/client/main.cpp
=> Initial event handling

src/Actions.hpp, src/Server.cpp, src/Server.hpp, src/game/GameFSM.hpp, src/main.cpp, src/network/MessageRouter.cpp, src/network/MessageRouter.hpp, test/client/main.cpp
This implements registration and UUID assignment for Player clients.
=> Client initialization

src/Actions.hpp, src/Events.hpp, src/Server.cpp, src/game/ChoiceHandling.hpp, src/game/ChoicePhaseFSM.hpp, src/game/EquipChoiceHandling.hpp, src/game/GameFSM.hpp, src/game/Guards.hpp, src/network/MessageRouter.hpp, src/util/Format.hpp, test/client/main.cpp
=> Implementierung der Ausrüstungsphase

.github/workflows/combine.yml
combine develop branch, not master
=> fix repomerge

exampleConfig/matchconfig.json, src/game/GameFSM.hpp
=> Roulette table init

src/Server.cpp, src/game/ChoiceHandling.hpp, src/game/ChoicePhaseFSM.hpp, src/game/Guards.hpp, src/util/ChoiceSet.cpp, src/util/ChoiceSet.hpp, test/client/main.cpp
needs https://github.com/SoPra-Team-17/LibCommon/pull/263
=> Fix choice phase

src/CMakeLists.txt, src/Server.cpp, src/Server.hpp, src/network/MessageRouter.cpp, src/network/MessageTypeTraits.hpp, test/client/main.cpp
Filter incoming messages depending on the role of the client that sent them. This should improve the robustness of the fsm.
=> Message filter

src/network/MessageRouter.cpp
=> check client id in messages

src/game/GameFSM.hpp
=> send game status after equip phase

src/game/ChoicePhaseFSM.hpp, src/game/OperationHandling.hpp
Depends on the associated PR in LibCommon.
=> add anti plague mask

src/Actions.hpp, src/Events.hpp, src/Server.cpp, src/Server.hpp, src/game/GameFSM.hpp, src/game/OperationHandling.hpp
=> janitor and cat movement

src/Server.hpp, src/game/GameFSM.hpp, src/game/OperationHandling.hpp
=> add random safe index initialization

src/Server.hpp, src/game/GameFSM.hpp, src/game/Guards.hpp
fixes #96 
Spectators should now be able to join anytime, nevertheless this will be checked in #97
=> fix spectator game start

src/Actions.hpp, src/Server.hpp, src/game/GameFSM.hpp, src/util/Util.hpp, test/client/CMakeLists.txt, test/client/main.cpp
fixes #101 
fixes #103 
Optionale Meta-Informationen werden noch nicht unterstützt
CI needs https://github.com/SoPra-Team-17/LibCommon/pull/299
=> Metainformation fixes

src/network/MessageRouter.cpp
=> add reconnect to allowed initial messages

src/game/OperationHandling.hpp, src/util/Util.cpp, src/util/Util.hpp
=> end turn if character is stuck in fog

src/game/OperationHandling.hpp, src/util/Operation.cpp, src/util/Operation.hpp
Testen steht noch aus.
Edit: Mittlerweile primitiv getestet, funktioniert soweit.
=> add exfiltration to operation handling

src/network/MessageRouter.cpp
=> fix always discarding messages with correct clientID

src/Actions.hpp, src/game/GameFSM.hpp, src/game/Guards.hpp
Request operation if received/generated operation was invalid
fixes #139, relates to #140
=> Re-request operation

src/Events.hpp, src/Server.hpp, src/game/OperationHandling.hpp
=> Gameend internal transition

src/Events.hpp, src/Server.hpp, src/game/GameFSM.hpp, src/game/OperationHandling.hpp
=> add turn phase timeout

src/network/MessageRouter.cpp
Avoids server crashes through completely wrong messages, that lack the required fields.
=> more try catch for message deserialization
